DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id INT NOT NULL AUTO_INCREMENT,
  firstname VARCHAR(255) DEFAULT NULL,
  lastname VARCHAR(255) DEFAULT NULL,
  pseudoname VARCHAR(255) NOT NULL,
  mail VARCHAR(255),
  password VARCHAR(255),
  credits INT DEFAULT 1000,
  PRIMARY KEY (`id`)
);
