DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id INT NOT NULL AUTO_INCREMENT,
  firstname VARCHAR(30) DEFAULT NULL,
  lastname VARCHAR(30) DEFAULT NULL,
  pseudoname VARCHAR(30) NOT NULL,
  mail VARCHAR(90),
  password VARCHAR(255),
  PRIMARY KEY (`id`)
);
