DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS roles;
CREATE TABLE roles (
id INT NOT NULL AUTO_INCREMENT,
name VARCHAR(15),
PRIMARY KEY (`id`)
);

CREATE TABLE users (
id INT NOT NULL AUTO_INCREMENT,
firstname VARCHAR(30) DEFAULT NULL,
lastname VARCHAR(30) DEFAULT NULL,
pseudoname VARCHAR(30)  NOT NULL,
mail VARCHAR(90),
birthdate DATE NOT NULL,
logdate DATE NOT NULL,
password VARCHAR(20),
roles_id INT,
PRIMARY KEY (`id`),
FOREIGN KEY (roles_id) REFERENCES roles(id)
);

